--1) What is the total revenue generated by each product category
with cte as (select p.product_category_name,(oi.price+oi.shipping_charges) as revenue from order_items oi join products p 
on oi.product_id=p.product_id)
select product_category_name,round(sum(revenue)::numeric,2) as total_revenue from cte
group by product_category_name
order by total_revenue desc

--2) Top 10 customers by total amount spent
select c.customer_id,sum(py.payment_value) as total_amount_spent from customers c join orders o on o.customer_id=c.customer_id
join payments py on o.order_id=py.order_id
group by c.customer_id
order by sum(py.payment_value) desc limit 10

--3) Monthly order count and revenue trend over time
select Extract(year from o.order_purchase_timestamp) as year, Extract(month from o.order_purchase_timestamp) as month,
count(distinct o.order_id) as total_orders,round(sum(oi.price+oi.shipping_charges):: numeric,2)as revenue 
from orders o join order_items oi on o.order_id=oi.order_id
group by Extract(year from o.order_purchase_timestamp),Extract(month from o.order_purchase_timestamp)

--4) What is the average delivery time (in days) by customer state
with cte as (
select c.customer_state,extract(day from(o.order_delivered_timestamp)-(o.order_purchase_timestamp)) as Delivery_time from 
customers c join orders o on o.customer_id=c.customer_id
)
select customer_state,round(avg(delivery_time):: numeric,2) as Avg_delivery_time from cte
group by customer_state

--5) What is the distribution of payment types used, and their total value
select distinct(payment_type),round(sum(payment_value):: numeric,2),count(*) as payment_type from payments
group by payment_type

--6) Which customers have placed more than 1 order 
select c.customer_id,count(o.order_id) as total_orders from customers c left join orders o on c.customer_id=o.customer_id 
group by c.customer_id
having count(order_id)>1

--7) What are the top 5 products by total revenue, excluding the "toys" category
select oi.product_id,p.product_category_name,round(sum(oi.price+oi.shipping_charges):: numeric,2) as total_revenue from  
order_items oi join products p on oi.product_id=p.product_id
where p.product_category_name !='toys'
group by p.product_category_name,oi.product_id
order by sum(oi.price+oi.shipping_charges) desc limit 5

--8) Which orders were delivered later than their estimated delivery date, and by how many days
select order_id, extract(day from (order_delivered_timestamp - order_estimated_delivery_date)) as delay_days
from orders
where order_delivered_timestamp > order_estimated_delivery_date
order by delay_days desc;

--9) Rank customers by total spend within their state
select c.customer_id,c.customer_state,sum(oi.price+oi.shipping_charges) as total_spend,
dense_rank() over(partition by c.customer_state order by sum(oi.price+oi.shipping_charges)desc) as rnk  from customers c
join orders o on c.customer_id=o.customer_id join order_items oi on oi.order_id=o.order_id
group by c.customer_id,c.customer_state

--10) What is the running (cumulative) monthly revenue total over time
with cte as (
select extract(year from o.order_purchase_timestamp) as year, extract(month from o.order_purchase_timestamp) as month,round(sum(oi.price+oi.shipping_charges)::numeric,2) as revenue from 
orders o join order_items oi on o.order_id=oi.order_id
group by extract(year from o.order_purchase_timestamp),extract(month from o.order_purchase_timestamp))
select year,Month,revenue,sum(revenue)over(order by year, month) as running_monthly_revenue from cte

--11)  For each order, show the order value alongside the customer's average order value
with cte as (select c.customer_id,o.order_id,round(sum(oi.price+oi.shipping_charges):: numeric,2) as order_value from
orders o join customers c on o.customer_id=c.customer_id join order_items oi on o.order_id = oi.order_id
group by c.customer_id,o.order_id)
select customer_id,order_id,order_value,round(avg(order_value)over(partition by customer_id)::numeric,2) as Average_Order_Value from cte

--12) What is the month-over-month revenue growth percentage
with cte as (
select extract(year from o.order_purchase_timestamp) as year, extract(month from o.order_purchase_timestamp) as month,
round(sum(oi.price+oi.shipping_charges)::numeric,2) as revenue from 
orders o join order_items oi on o.order_id=oi.order_id 
group by extract(year from o.order_purchase_timestamp),extract(month from o.order_purchase_timestamp))

select year,month,revenue,lag(revenue,1)over(order by year,month)as month_growth,
round((revenue-lag(revenue,1)over(order by year,month))/lag(revenue,1)over(order by year,month)*100::numeric,2) as "MOM_Growth%"
from cte

--13) Find the top 3 product categories by revenue per state
with cte as (select c.customer_state,p.product_category_name,round(sum(oi.price+oi.shipping_charges)::numeric,2) as revenue,
dense_rank()over(partition by c.customer_state order by sum(oi.price+oi.shipping_charges)desc) as rnk 
from customers c join orders o on o.customer_id=c.customer_id join order_items oi on o.order_id=oi.order_id
join products p on p.product_id=oi.product_id
group by c.customer_state,p.product_category_name)

select customer_state,product_category_name,revenue from cte
where rnk <=3

--14) Calculate what % of total revenue each payment type contributes
select py.payment_type,round(sum(oi.price+oi.shipping_charges)::numeric,2) as revenue,count(*)
from payments py join orders o on o.order_id=py.order_id join order_items oi on oi.order_id=o.order_id
group by py.payment_type
























